### ISSUE TITLE
Masking doesn't work using escaped double quotes

### ISSUE THREAD

**Issue by lucasfersil** [IBM/Drain3#12]
Regex presents problem when double quotes are used, showing a json decoder error message.

**Comment by davidohana** [comment]
Can you provide a sample regex with the problem and the stack trace of the error?

**Comment by lucasfersil** [comment]
Sure, although it can be a typo of mine:
 
{"regex_pattern":"((?<=C\\=\\").*(?=\\"))", "mask_with": "SENTMSG"}   

it leads to:

Traceback (most recent call last):
  File "drain3_ex.py", line 43, in <module>
    template_miner = TemplateMiner(persistence)
  File "/root/venvdrain/lib64/python3.8/site-packages/drain3/template_miner.py", line 32, in __init__
    self.masker = LogMasker()
  File "/root/venvdrain/lib64/python3.8/site-packages/drain3/masking.py", line 55, in __init__
    m = json.loads(config.get('DEFAULT', 'masking', fallback="[]"))
  File "/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 7 column 31 (char 578)

But it works correctly using single escape on double quotes:

{"regex_pattern":"((?<=C\\=\").*(?=\"))", "mask_with": "SENTMSG"}

Result:

 C=\"<SENTMSG>\"

**Comment by davidohana** [comment]
I think that your regex pattern is illegal. The " in \\" is treated as the end of regex_pattern json string.
Maybe you meant to do: ```{"regex_pattern":"((?<=C\\=\\\").*(?=\\\"))", "mask_with": "SENTMSG"}``` ?

**Comment by lucasfersil** [comment]
"((?<=C\\\\=\\\\\\").\*(?=\\\\\\"))" 
and
"((?<=C\\\\=\\\").\*(?=\\\"))"

are working, it's just more difficult to read than traditional LogPai implementation due to many back slashes.
