### ISSUE TITLE
Enhancement: make the persistence requirements optional

### ISSUE THREAD

**Issue by barakreif** [IBM/Drain3#13]
Using [extran_require](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies)  so no need to install unneeded dependencies. 

I am happy to PR if you feel this is useful.

**Comment by davidohana** [comment]
Thanks, good idea. Will work on it.

**Comment by davidohana** [comment]
Done, released v0.7.5
