### ISSUE TITLE
Drain3 does not extract text patterns?

### ISSUE THREAD

**Issue by vikramriyer** [IBM/Drain3#17]
Thanks for putting this together team. I have been trying to use Drain and came across this issue. 

```
'user=mike ip=unknown-ip-addr cmd=Metastore shutdown complete',
'user=mike ip=unknown-ip-addr cmd=Shutting down the object store',
'user=smith ip=unknown-ip-addr cmd=Metastore shutdown complete',
'user=smith ip=unknown-ip-addr cmd=Shutting down the object store',
'user=jackson ip=unknown-ip-addr cmd=Metastore shutdown complete',
'user=jackson ip=unknown-ip-addr cmd=Shutting down the object store',
'user=bob ip=unknown-ip-addr cmd=Metastore shutdown complete',
'user=bob ip=unknown-ip-addr cmd=Shutting down the object store'
```

So, ideally, the patterns look similar i.e. of the form 

```
user=<*> ip=<*> cmd=<*>
```

But, the drain algorithm does not pick this up. I have tried with several params of sim_th, depth, and max_children. 

Am I missing something? Can someone help?

**Comment by davidohana** [comment]
Hello, 

This question is better asked at the original Drain repo: https://github.com/logpai/logparser/issues 
However, I can tell from my experience that:
* Simple and well-defined constructs like IP are better masked with regex before passing to Drain (use masking feature of drain3 for that)
* Drain might have difficulties with multiple-words variables like `cmd`.  You might try to mask those too.
* The `user` variable ion your example should be de-templated without a problem.

**Comment by vikramriyer** [comment]
Thanks for answering and pointing me to the original repo, David. However, just a follow-up, I did not quite grasp what you meant by `multuple-words variables`.

**Comment by davidohana** [comment]
I meant variables that can hold multiple words, or a sentence, like cmd in your example

**Comment by vikramriyer** [comment]
Awesome, thanks. So should I assume that the pattern for the word `user` was correctly identified because it's an English dictionary valid word?

**Comment by davidohana** [comment]
No, no relation to a dictionary, just because it's a single word.

**Comment by vikramriyer** [comment]
Got it! Thanks for patiently answering David.
