### ISSUE TITLE
After each restart, the first log is cluster_ created

### ISSUE THREAD

**Issue by ieven** [IBM/Drain3#24]
No matter which persistence method I use, the first log after restart is cluster_ created。 And the same results don't merge。Is this a bug ?

**Comment by ieven** [comment]
Only 0.9.0 has problems, other versions is ok.

**Comment by davidohana** [comment]
Thanks, I think this bug was already fixed at https://github.com/IBM/Drain3/pull/23
I am working to add unit tests for this and few other additions. Will release a fixed version soon.

**Comment by davidohana** [comment]
v0.9.1 released
