### ISSUE TITLE
comparison of type int with type str in function add_seq_to_prefix_tree

### ISSUE THREAD

**Issue by heiner0815** [IBM/Drain3#28]
Hi,
due to a type mismatch between `current_depth` and `token_count` the boolean flag `is_last_token` is always false.
It should read `int(tocken_count)`.

https://github.com/IBM/Drain3/blob/f004cb235f92646b3cfdb4ed6680765e9f944d06/drain3/drain.py#L136

This a test which fails:
```
    def test_one_token_message(self):
        model = Drain()
        cluster, change_type = model.add_log_message("oneTokenMessage")
        self.assertEqual("cluster_created", change_type, "1st check")
        cluster, change_type = model.add_log_message("oneTokenMessage")
        self.assertEqual("none", change_type, "2nd check")
```
PS: Thanks for fixing the other two issues so quickly

**Comment by davidohana** [comment]
Thanks, fixed in v0.9.3 + added your unit test to the codebase.
