### ISSUE TITLE
Duplicate clusters after loading saved state

### ISSUE THREAD

**Issue by raphaelschmidt** [IBM/Drain3#29]
Dear all, 

when processing the same batch of logs twice everything works as expected, but when loading the state file again and process the same batch of logs, some new, duplicate, clusters will be created. 

Here you can see the second run on the same batch of logs after reloading the state file:
<img width="421" alt="2021-03-02 14_26_05-JupyterLab" src="https://user-images.githubusercontent.com/74202569/109656008-3a4cf480-7b64-11eb-9750-5d5525e554f1.png">

And here are all clusters:
<img width="666" alt="2021-03-02 14_31_14-JupyterLab" src="https://user-images.githubusercontent.com/74202569/109656116-5d77a400-7b64-11eb-87f5-d9a9c9bcc64c.png">

Shouldn't the behavior after loading the state file before processing the logs the second time be the same as when processing them twice without loading the state file?

Thank you in advance!

**Comment by davidohana** [comment]
Hello

Please make sure you use the latest release of Drain 3 (0.9.2) as we had some bugs related to this issue.
If the problem still exists in the new version, can you profile a code sample/unit test demonstrating the issue?

David

**Comment by raphaelschmidt** [comment]
Hi @davidohana,

thanks for your quick reply.
Seems like updating fixed it.

btw: great work. =)
