### ISSUE TITLE
Matching float numbers

### ISSUE THREAD

**Issue by aguinaldoabbj** [IBM/Drain3#35]
Hi,

I'm trying to match and mask a float number ("+12", "-12", "-3.14", ".314e1", etc) in a sentence. I've tried several regexes, like this one: "[^a-zA-Z:]([-+]?\d+[\.]?\d*)"

Althoug this regex works when I run in python `re.findall("[^a-zA-Z:]([-+]?\d+[\.]?\d*)", 'Hi, -1.25 is a float') `,
if I add it to the mining instructions as 

`{"regex_pattern":"(?<![a-zA-Z:])[-+]?\d*\.?\d+", "mask_with": "FLO"},`

the masking doesn't occur, I get a <:*:> in the mined template.

What am I doing wrong?

**Comment by davidohana** [comment]
Drain will work well with floats even if you mask only integers because you will get a template like `<NUM>.<NUM>` for floats in this case.
If you still want a float template, please check that you escape `\` properly as `\\`  in the `.ini` file.

**Comment by aguinaldoabbj** [comment]
@davidohana Thanks for your reply.
You mean that by using the "default" regexes in drain3.ini ?
By using those default regexes I cannot get a template with <NUM>.<NUM> for floats like you said. 

For example, I have this sentence:
`Rate of Change Rate 0.572213 Limit 0.1`
And the drained template for that is `Rate of Change Rate <:*:> Limit <:*:>`

That's why I'm trying a new regex in the .ini file . I followed your tip and scaped \ in the .ini file:
` {"regex_pattern":"(?<![a-zA-Z:])[-+]?\\d*\\.?\\d+", "mask_with": "FLO"},`

Still no luck. The regex works flawlessly with re.findall()

**Comment by davidohana** [comment]
The order of masks also matters. 
Please put float mask before int masks. If some param occurrences are mixed - some float and some int, it can also cause this issue so you may need to capture both in the same mask regex.
