### ISSUE TITLE
How to purge no-use existing cluster after running for a while

### ISSUE THREAD

**Issue by a4455669** [IBM/Drain3#40]
Dear all,
In production, data will drift in some conditions and some of old cluster will never happen again. The new log will never comes in the cluster so the result is not impact. However, the performance is. As number of cluster increase, the running performance will degrade because consuming more time on comparing existing cluster. 

So, here’s the question: **Are there any interface in kernel or suggestions to automatically detect no-use cluster and purge it?**

Thanks to all the developers, drain3 is an amazing kerne.

**Comment by davidohana** [comment]
Hello, 

You can check if the `max_clusters​` argument can help in your case.
please see https://github.com/IBM/Drain3#memory-efficiency
