### ISSUE TITLE
Monitor the use of frequently used cluster

### ISSUE THREAD

**Issue by stanchion-bishoyi** [IBM/Drain3#41]
How to monitor which clusters are being used frequently? By monitoring means that saving the cluster id of those recent clusters which has been indicated by following 3 change_type.
> change_type - indicates either if a new template was identified, an existing template was changed or a message was added to an existing cluster.

**Comment by davidohana** [comment]
You can check the sizes of the clusters in the `id_to_cluster` dict, but that will give you a full historic answer and not a recent indication.  If you want to limit this only to recent usage, you can add a custom solution based on the `change_type` results.
Also, you can check if https://github.com/IBM/Drain3#memory-efficiency feature can help in your use case.

**Comment by stanchion-bishoyi** [comment]
Thank You.. I got it
