### ISSUE TITLE
I cannot get value vector from match

### ISSUE THREAD

**Issue by dobrowol** [IBM/Drain3#47]
Hi,

I would like to get value vector from log, not only cluster it matches. How to get it?

Match returns only LogCluster.

` def match(self, log_message: str) -> LogCluster:`

**Comment by davidohana** [comment]
You can use `get_parameter_list()` for that.
See example: https://github.com/IBM/Drain3/blob/0f7842cc577bb9ecc169476fc4638047b7cf6518/examples/drain_stdin_demo.py#L60
