### ISSUE TITLE
Error when running the example.

### ISSUE THREAD

**Issue by zequeira** [IBM/Drain3#55]
Hi,

I'm trying to run the example: `drain_bigfile_demo.py`, but I'm getting the error:

`ImportError: cannot import name 'KeysView' from 'collections' (C:\Miniconda3\...\lib\collections\__init__.py)`
The code is failing on this line of code:
`from drain3 import TemplateMiner`

To provide a bit of context, I installed Drain3 via: `pip3 install drain3`, my python version is 3.10.0.
Thanks for your help.
Regards.

**Comment by davidohana** [comment]
Thank you for reporting this. A compatibility issue was introduced in Python 3.10. 
Fixed now - in Drain3 v0.9.10.
