### ISSUE TITLE
specify a log file 

### ISSUE THREAD

**Issue by EtafHadda** [IBM/Drain3#61]
thanks for all this effort

sorry about this simple question. I need to put a file from my system to be mined. how can I do that?
I need to know how can I put options like (file, sim_th and max_clusters )

thanks a lot

**Comment by davidohana** [comment]
[This](https://github.com/IBM/Drain3/blob/master/examples/drain_bigfile_demo.py) example demonstrates working with input log files. Basically, you create a `TemplateMiner` instance and you can pass a config object with the options you need.
Then you read the log file line-by-line and feed it to the template miner using `add_log_message()`.
