### ISSUE TITLE
[Question] Drain DAG version

### ISSUE THREAD

**Issue by boernd** [IBM/Drain3#9]
Hi,

as far as I can see from the README this is the tree based implementation. Do you als plan to support the DAG based version (https://arxiv.org/pdf/1806.04356.pdf)? I think this is the code from the logpai repo: https://github.com/logpai/logparser/blob/dev/logparser/Drainjournal.py
Not exactly sure how it compares to the original algorithm regarding perf, ... but the automated paramter tuning or log group merging features sound interesting.

**Comment by davidohana** [comment]
Hi, the Drainjournal version is still in dev branch and no evaluation is available yet. When it is more mature, we may support it as well. Of-course, we also accept PRs.

**Comment by boernd** [comment]
Thanks for the quick answer!
